FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get -y install --no-install-recommends \
    wget \
    unzip \
    perl \
    cpanminus \
    ca-certificates \
    make \
    jq \
    pandoc \
    texlive-latex-base \
    texlive-latex-recommended \
    # Dependencies for wkhtmltopdf
    fontconfig \
    libfreetype6 \
    libjpeg62-turbo \
    libpng16-16 \
    libx11-6 \
    libxcb1 \
    libxext6 \
    libxrender1 \
    xfonts-75dpi \
    xfonts-base \
    # Perl dependencies from system packages (faster than CPAN)
    libxml-writer-perl \
    libarchive-zip-perl \
    libjson-perl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install wkhtmltopdf from official releases
RUN wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb -O /tmp/wkhtmltox.deb \
    && dpkg -i /tmp/wkhtmltox.deb || apt-get install -f -y \
    && rm -f /tmp/wkhtmltox.deb

# Install only required Perl modules from CPAN (multi-stage for better caching)
RUN cpanm --notest --quiet \
    Excel::Writer::XLSX

# Download and install lynis-report-converter
RUN wget -q https://github.com/wearetechnative/lynis-report-converter/archive/refs/heads/master.zip -O /tmp/master.zip \
    && unzip -q /tmp/master.zip -d /opt \
    && cd /opt/lynis-report-converter-master/ \
    && perl Makefile.PL \
    && make \
    && make install \
    && cp lynis-report-converter.pl /usr/local/bin/ \
    && chmod +x /usr/local/bin/lynis-report-converter.pl \
    && rm -rf /tmp/* /root/.cpanm /opt/lynis-report-converter-master

# Set working directory
WORKDIR /data

# Optimized entrypoint - directly run converter
# Default to JSON output to stdout
# Note: Running as root to read lynis report (generated by root)
ENTRYPOINT ["/usr/local/bin/lynis-report-converter.pl"]
CMD ["-j", "-i", "/data/lynis-report.dat", "-o", "/dev/stdout"]
