# Pinned: debian:latest drifts across releases (it is trixie as of 2026-09),
# while this image only needs a stable base for a single Perl script.
FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

# lynis-report-converter.pl lazily `require`s its format modules per output mode.
# This image only ever runs the JSON path (see CMD), which needs JSON alone.
# XML::Writer, Excel::Writer::XLSX and HTML::HTMLDoc are deliberately absent.
RUN apt-get update && apt-get -y install --no-install-recommends \
    ca-certificates \
    git \
    libjson-perl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Pinned to a commit so the image contents do not depend on the build date.
# Upstream: https://github.com/wearetechnative/lynis-report-converter
ARG CONVERTER_COMMIT=7a26d37cc3a0ca53ea259eee2b23f1e165ea4e6b
RUN git init -q /tmp/lrc \
    && git -C /tmp/lrc remote add origin https://github.com/wearetechnative/lynis-report-converter.git \
    && git -C /tmp/lrc fetch -q --depth 1 origin "${CONVERTER_COMMIT}" \
    && git -C /tmp/lrc checkout -q FETCH_HEAD \
    && cp /tmp/lrc/lynis-report-converter.pl /usr/local/bin/ \
    && chmod +x /usr/local/bin/lynis-report-converter.pl \
    && rm -rf /tmp/lrc

# Set working directory
WORKDIR /data

# Optimized entrypoint - directly run converter
# Default to JSON output to stdout
# Note: Running as root to read lynis report (generated by root)
ENTRYPOINT ["/usr/local/bin/lynis-report-converter.pl"]
CMD ["-j", "-i", "/data/lynis-report.dat", "-o", "/dev/stdout"]
